### ISSUE TITLE
Feature request: add Html.map

### ISSUE THREAD

**Issue by benjamin-thomas** [hbr/fmlib#6]
Hello!

Playing with your library, I wanted to reproduce [this example](https://github.com/benjamin-thomas/elm-playground/blob/595e75a1968b56effe01164603bef406b82453e3/parent-children-communication/src/WithoutStoringPosition/Main.elm#L85)

However, `Html.map` seems to be missing.

Are you planning on adding it?

**Comment by hbr** [comment]
Hello Benjamin,

thanks for the request. Certainly Html.map is a missing feature. I don’t know why I have overlooked it. It will probably present in the next release.

Regards
Helmut

**Comment by hbr** [comment]
The feature `Html.map` is available in the source code in the branch `browser`. I don't know when to make the next release to make it available officially.

Is the feature urgent for you?

**Comment by benjamin-thomas** [comment]
Awesome thanks!

I'm just playing at the moment, so nothing's urgent :)

I'd love to try the feature out so I think I'll try to get by with `opam pin` (I've only used it once, but I think it should work).

Otherwise, I'll have to learn how to do vendoring properly (I remember facing difficulties trying to find the right approach with dune)

If you have any tips I'm all ears though :)

**Comment by benjamin-thomas** [comment]
So I just copied the repo next to my dune file and it works wonderfully :)

Mapping works as advertised :)

Added bonus, I can also easily explore the library code now.

I'll have to play with git submodules next. Dune has a vendoring feature but I still couldn't figure out how to make it work

**Comment by hbr** [comment]
Great. Any comments and hints are welcome.

**Comment by hbr** [comment]
Hi Benjamin,

The functions `Html.map` and `Attribute.map` are now available in the version 0.5.5 of fmlib.

Regards
Helmut
